clusters:
- cluster:
    server: http://127.0.0.1:8080
  name: kwok-kwok
contexts:
- context:
    cluster: kwok-kwok
    user: kwok-kwok
  name: kwok-kwok
current-context: kwok-kwok
kind: Config
preferences: {}
users: null