apiVersion: v1
kind: Service
metadata:
  name: subcluster
spec:
  selector:
    app: subcluster
  type: NodePort
  ports:
  - name: http-kube
    port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30080
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53