apiVersion: v1
kind: ConfigMap
metadata:
  name: subcluster
data:
  kwok.yaml: |
    kind: KwokctlConfiguration
    apiVersion: config.kwok.x-k8s.io/v1alpha1
    options:
      disable:
      - kwok-controller
      kubeApiserverCertSANs: # TODO: remove this
      - kubernetes
    componentsPatches:
    - name: kube-apiserver-insecure-proxy
      extraArgs:
      - key: disable-filter 
        value: 'true'
    - name: kube-controller-manager
      extraArgs:
      - key: controllers
        value: '*,-cloud-node-lifecycle-controller,-endpoints-controller,-endpointslice-controller,-service-cidr-controller,-service-lb-controller,-node-ipam-controller'
  Corefile: |
    .:53 {
        health :8180
        ready :8181
        errors

        kubernetes cluster.local in-addr.arpa ip6.arpa {
           endpoint http://127.0.0.1:8080
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
  kubeconfig: |
    users: null
    clusters:
    - cluster:
        server: http://127.0.0.1:8080
      name: kwok-kwok
    contexts:
    - context:
        cluster: kwok-kwok
        user: kwok-kwok
      name: kwok-kwok
    current-context: kwok-kwok
    kind: Config
    preferences: {}
    users: null
