name: Test

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        shell: bash
        run: |
          make build

      - name: Up
        shell: bash
        run: |
          make up

      - name: E2e
        shell: bash
        run: |
          make e2e

      - name: Conformance
        shell: bash
        run: |
          make conformance
